home = read.csv(file.choose(), header = T)
attach(home)
home
summary(home)
mm<-lm(Homeowners~Immigrant)
mm
summary(mm)
plot(Homeowners~Immigrant)
abline(mm)
abline(mm,col=2,lwd=3)
newImmigrantdata <- data.frame(Immigrant = c(0,  20))
newImmigrantdata
mm %>% predict(newImmigrantdata)
abline(mm)
abline(mm,col=3,lwd=3) 
attributes(mm)
mm$coefficients
plot(home$Income,home$Homeowners)
library(ggplot2)
qplot(home$Income,home$Homeowners)
qplot(Income,Homeowners, data=home)
ggplot(home,aes(x=Income,y=area))+geom_point()
plot(home$Income,home$Population, type="l")
points(home$Income,home$Population)
lines(home$Income,home$Population/2, col="red")
points(home$Income,home$Population/2, col="red")
qplot(home$Income,home$Population, geom="line")
ggplot(home,aes(x=Income,y=area)) +geom_line()+geom_point()

barplot(home$Population,names.arg=home$City)
table(home$City)
barplot(table(home$Population))
qplot(home$Income,binwidth=40)
qplot(factor(home$Income))
ggplot(home,aes(x=factor(Income)))+geom_bar()
hist(home$Income)
hist(home$Income, breaks=10)
hist(home$Income, breaks=5)
qplot(Income,data=home, binwidth=4 )
ggplot(home,aes(x=Income))+geom_histogram(binwidth =4)
plot(home$Income,home$Population)
boxplot(Income ~ Population)
boxplot(Income ~ Population+area)
qplot(Income,Population, geom = "boxplot")
ggplot(home,aes(x=Income,y=Population))+geom_boxplot()
qplot(interaction(Income,Population),area,geom="boxplot")
ggplot(home, aes(x=interaction(Income,Population),y=area))+geom_boxplot()
      